#!/bin/bash
# CONFIGURATION
[ -f csrgen.conf ] && . csrgen.conf

if ! test "x$SUBJECT" == "x" -a "x$SUBJECT" == "x/C=XX/O=Default Organisation/OU=Default OU/CN="
then
	[ -f csrgen.conf.default -a ! -f csrgen.conf ] && cp csrgen.conf{.default,}
	echo -e 'Oops! you forgot to edit \033[1mcsrgen.conf\033[0m\n' > /dev/stderr
	exit 1
fi

# INITIAL VALUES
CN=
ALT=
altCount=0
totalCount=0
csrCount=0
{ cat $@; echo; } | while read line
do
	[ "${line:0:1}" == "#" ] && continue
	if [ "$line" == "" ]
	then
		if [ "$CN" != "" ]
		then
			echo -en "[\033[36mbusy\033[0m] \033[1m${CN}\033[0m (${altCount})" > /dev/stderr
			[ -e "$CN.ssl" ] && rmdir "$CN.ssl" > /dev/null 2>&1
			if [ -e "$CN.ssl" ]
			then
				echo -e "\r[\033[35mexst\033[0m]" > /dev/stderr
			else
				export ALTNAME="$ALT"
				mkdir "${CN}.ssl"
				openssl req -batch -new -nodes \
					-keyout "${CN}.ssl/key-${CN}.pem" \
					-out "${CN}.ssl/csr-${CN}.pem" \
					-config openssl.cnf \
					-subj "${SUBJECT}${CN}" \
						> "${CN}.ssl/csr-${CN}.log" \
				2>&1 \
				&& echo -e "\r[\033[32m ok \033[0m]" > /dev/stderr \
				|| { echo -e "\r[\033[31mfail\033[0m]\n" > /dev/stderr; exit 1; } \

				csrCount=$(expr $csrCount + 1)
		rmdir "${CN}.ssl" > /dev/null 2>&1
			fi
		fi
		CN=
		ALT=
		altCount=0
	else
		trimline=$(echo $line | tr -d ' ')
		[ "$CN" == "" ] && CN="$trimline"
		[ "$ALT" == "" ] && ALT="DNS:$trimline" || ALT="$ALT","DNS:$trimline"
		altCount=$(expr $altCount + 1)
		totalCount=$(expr $totalCount + 1)
	fi
done

